version: '3.8'

services:
  mongodb:
    image: mongo:7-jammy
    container_name: mongodb-test
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=jobprocessor_test
    volumes:
      - mongodb_test_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.admin.ping()"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis-test
    ports:
      - "6379:6379"
    volumes:
      - redis_test_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  mongodb_test_data:
  redis_test_data: